### ISSUE TITLE
Clarifications about `:discussion`s

### ISSUE THREAD

**Issue by ema-fox** [sparkboard/sparkboard#110]
What is the relationship between :discussion and :project entities?
- For the most part there is at most one discussion pointing at a project but there are two projects which have two discussion each pointing at them[1]. 
If these are just the result of a bug would it make sense to merge them in the migration?
 - if yes, does anything speak against putting the discussion attributes directly on the project entity and not having separate discussion entities?

Currently discussions point at posts via `:discussion/posts`, my usual approach would be to have posts point at discussions via `:post/discussion`.
 - advantage would be that creating/deleting a post only touches the post entity without having to touch the discussion entity.
 - does anything speak against that?

I assume we want to display the discussion for a project somewhere at the bottom of the project modal. Correct?

[1] a446024e-13c0-32ee-a028-a961eb930404 and a4c2642f-0989-32d6-98d1-2e7858f1f69e

**Comment by mhuebert** [comment]
> What is the relationship between :discussion and :project entities?
> * there are two projects which have two discussion each pointing at them[1]. If these are just the result of a bug would it make sense to merge them in the migration?

Yes, a bug - can be merged. Or, if it's from an old board, dropped. (It would be ok for the migration to be mildly lossy for stuff that's >2 years old if it saves complexity / dev time)

> * if yes, does anything speak against putting the discussion attributes directly on the project entity and not having separate discussion entities?

That sounds reasonable to me.

> Currently discussions point at posts via `:discussion/posts`, my usual approach would be to have posts point at discussions via `:post/discussion`. advantage would be that creating/deleting a post only touches the post entity without having to touch the discussion entity.

Also fine by me.

> I assume we want to display the discussion for a project somewhere at the bottom of the project modal. Correct?

Yes. That's where they are in the current/old version. (Feel free to mess around on demo.sparkboard.com)

Thank you for digging into this.
